-- Set leader key early before any keymaps are defined
vim.g.mapleader = " "
vim.g.maplocalleader = " "

require("boshoffwillem.plugins")
require("boshoffwillem.appearance")
require("boshoffwillem.comment")
require("boshoffwillem.filetype")
require("boshoffwillem.flutter")
require("boshoffwillem.format")
require("boshoffwillem.kotlin").setup()
require("boshoffwillem.kotlin").setup_keymaps()
require("boshoffwillem.kotlin").setup_autocommands()
require("boshoffwillem.swift").setup()
require("boshoffwillem.swift").setup_keymaps()
require("boshoffwillem.swift").setup_autocommands()
require("boshoffwillem.info")
-- require("boshoffwillem.indent_blank_line")
require("boshoffwillem.keymaps")
require("boshoffwillem.neo-tree").setup()
require("boshoffwillem.neo-tree").setup_keymaps()
require("boshoffwillem.lint")
require("boshoffwillem.lsp")
require("boshoffwillem.tree-sitter")
require("boshoffwillem.options")
require("boshoffwillem.tabnine")
require("boshoffwillem.telescope")
require("boshoffwillem.toggle_term")
require("boshoffwillem.undotree")
require("boshoffwillem.version_control")
require("boshoffwillem.dap")
require("boshoffwillem.universal-keybinds").setup()
require("boshoffwillem.csharp").setup()
require("boshoffwillem.csharp").setup_keymaps()
require("boshoffwillem.csharp").setup_autocommands()
require("boshoffwillem.neotest").setup()
require("boshoffwillem.neotest").setup_keymaps()
require("boshoffwillem.dotnet-utils").setup_keymaps()
