require("boshoffwillem.plugins")
require("boshoffwillem.appearance")
require("boshoffwillem.comment")
-- require("boshoffwillem.dap")
require("boshoffwillem.filetype")
require("boshoffwillem.format")
require("boshoffwillem.info")
require("boshoffwillem.indent_blank_line")
require("boshoffwillem.keymaps")
require("boshoffwillem.lint")
require("boshoffwillem.lsp")
require("boshoffwillem.options")
require("boshoffwillem.tabnine")
require("boshoffwillem.telescope")
require("boshoffwillem.toggle_term")
require("boshoffwillem.undotree")
require("boshoffwillem.version_control")
require("boshoffwillem.tree-sitter")
